"""add hardware and software tables

Revision ID: bb8d7d00ebed
Revises: efcc60df955f
Create Date: 2026-07-07 23:09:50.108451

"""
from alembic import op
import sqlalchemy as sa


revision = 'bb8d7d00ebed'
down_revision = 'efcc60df955f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hw_boards',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('revision', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', 'revision', name='uq_board_name_rev')
    )
    op.create_index(op.f('ix_hw_boards_project_id'), 'hw_boards', ['project_id'], unique=False)
    op.create_table('sw_modules',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('module_type', sa.String(length=20), nullable=False),
    sa.Column('repo_url', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_module_name')
    )
    op.create_index(op.f('ix_sw_modules_project_id'), 'sw_modules', ['project_id'], unique=False)
    op.create_table('bom_items',
    sa.Column('board_id', sa.BigInteger(), nullable=False),
    sa.Column('part_name', sa.String(length=200), nullable=False),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['hw_boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_items_board_id'), 'bom_items', ['board_id'], unique=False)
    op.create_table('hw_fabrications',
    sa.Column('board_id', sa.BigInteger(), nullable=False),
    sa.Column('fab_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['hw_boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hw_fabrications_board_id'), 'hw_fabrications', ['board_id'], unique=False)
    op.create_table('sw_versions',
    sa.Column('module_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('released_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['sw_modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'version', name='uq_module_version')
    )
    op.create_index(op.f('ix_sw_versions_module_id'), 'sw_versions', ['module_id'], unique=False)
    op.create_table('sw_builds',
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('build_no', sa.String(length=50), nullable=False),
    sa.Column('commit_hash', sa.String(length=64), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['sw_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sw_builds_version_id'), 'sw_builds', ['version_id'], unique=False)
    op.create_table('sw_deployments',
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['sw_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sw_deployments_version_id'), 'sw_deployments', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sw_deployments_version_id'), table_name='sw_deployments')
    op.drop_table('sw_deployments')
    op.drop_index(op.f('ix_sw_builds_version_id'), table_name='sw_builds')
    op.drop_table('sw_builds')
    op.drop_index(op.f('ix_sw_versions_module_id'), table_name='sw_versions')
    op.drop_table('sw_versions')
    op.drop_index(op.f('ix_hw_fabrications_board_id'), table_name='hw_fabrications')
    op.drop_table('hw_fabrications')
    op.drop_index(op.f('ix_bom_items_board_id'), table_name='bom_items')
    op.drop_table('bom_items')
    op.drop_index(op.f('ix_sw_modules_project_id'), table_name='sw_modules')
    op.drop_table('sw_modules')
    op.drop_index(op.f('ix_hw_boards_project_id'), table_name='hw_boards')
    op.drop_table('hw_boards')
    # ### end Alembic commands ###
